name: Build Tent Card Generator

on:
  push:
    branches: [ main ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller launcher.py --onefile --noconsole --name TentCardGenerator

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Windows
          path: dist/TentCardGenerator.exe



  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Mac App
        run: |
          pyinstaller launcher.py --onefile --windowed --name TentCardGenerator

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Mac
          path: dist/TentCardGenerator



  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Linux Binary
        run: |
          pyinstaller launcher.py --onefile --name TentCardGenerator

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Linux
          path: dist/TentCardGenerator
