name: Build Tent Card Generator

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows EXE
        run: |
          python -m PyInstaller launcher.spec

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Windows   #v2
          path: dist/TentCardGenerator.exe


  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Mac App
        run: |
          python -m PyInstaller launcher.spec

      - name: Zip Mac App
        run: |
          cd dist
          zip -r TentCardGenerator-Mac.zip TentCardGenerator.app

      - name: Upload Mac Build
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Mac
          path: dist/TentCardGenerator-Mac.zip


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux Binary
        run: |
          python -m PyInstaller launcher.spec

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: TentCardGenerator-Linux
          path: dist/TentCardGenerator
